spring:
  profiles:
    active: local
    group:
      local: local, secret
      blue: blue, secret
      green: green, secret
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  env: blue

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
#  serverAddress: localhost
serverName: local_server

---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080

serverName: blue_server

---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081

serverName: green_server

